db:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: but
    POSTGRES_PASSWORD: but
web:
  build: .
  command: unicorn -c config/unicorn.rb
  environment:
    RAILS_ENV: development
  volumes:
    - .:/app
  ports:
    - 127.0.0.1:8080:8080
  links:
    - db
