db:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: but
    POSTGRES_PASSWORD: but
web:
  build: .
  restart: always
  command: unicorn -c config/unicorn.rb
  environment:
    RAILS_ENV: development
  volumes:
    - .:/app
  ports:
    - '8080:8080'
  links:
    - db
