db:
  image: postgres
  environment:
    POSTGRES_USER: but
    POSTGRES_PASSWORD: but
web:
  build: .
  command: sleep 100000000
  volumes:
    - .:/app
  ports:
    - '3000:3000'
  links:
    - db
  environment:
    BUNDLE_PATH: /vendor
