development:
  adapter: postgresql
  encoding: unicode
  host: db
  database: but
  username: but
  password: but
  pool: 4

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: db
  database: production
  username: but
  password: but
  pool: 4

staging:
  adapter: postgresql
  encoding: unicode
  host: db
  database: staging
  username: but
  password: but
  pool: 4
