karma:
  kernteam: 5
  extended_kernteam: 3
  workshop_owner: 2
  helper_shift: 1
prices:
  early_bird: -5.00
  registration: 95.00
  first_day: 25.00
  other_days: 20.00
  tshirt: 0.00
  distances:
    1: 0.00
    2: -5.00
    3: -10.00
    4: -15.00
  rooms:
    acc_dorm: 0.00
    acc_none: 0.00
    acc_dorm_with_bath: 5.00
    acc_double: 15.00
    acc_family: 15.00
    acc_single: 20.00
dates:
  registrations_frozen: 2015-04-15
  votable_without_payment: 2013-04-11
bank:
  account: "Deutsches YFU Komitee e.V."
  iban: "DE 94 2008 0000 0908 0302 00"
  bic: "DRES DE FF 200"
categories:
  [ 0 , 2
  , 2
  , 2
  , 2
  , 4
  , 1
  , 2
  , 2
  , 2
  , 1
  , 1
  , 1
  , 1
  , 1
  , 2
  , 1
  , 1
  , 2
  , 1
  , 1
  , 1
  , 1
  , 1
  , 2
  , 2
  , 2
  , 2
  , 2
  , 1
  , 1
  , 1
  , 2
  , 2
  , 2
  , 3
  , 2
  , 2
  , 1
  , 1
  , 3
  , 3
  , 3
  , 4
  , 3
  , 3
  , 3
  , 3
  , 3
  , 2
  , 3
  , 3
  , 3
  , 3
  , 4
  , 3
  , 3
  , 3
  , 3
  , 2
  , 3
  , 3
  , 4
  , 3
  , 3
  , 3
  , 4
  , 4
  , 3
  , 3
  , 4
  , 4
  , 4
  , 4
  , 3
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 4
  , 3
  , 3
  , 3
  , 3
  , 4
  , 2
  , 2
  , 3
  , 2
  , 2
  ]
