basic_auth:
  name: 'but-team'
  password: 'eawWekecog'
features:
  login: true
  workshops: true
  workshop_choices: true
  motto: true
  haus: true
  zeitplan: true
  team: true
  mithelfen: true
  help: true
  music_wishes: true
  algorithm: true
